// Generated by CoffeeScript 1.8.0
'use strict';
var FeatureFlagCollection;

FeatureFlagCollection = require('./feature_flag_collection');

module.exports = function() {
  var contextGenerator, ruleGenerator, _ref;
  if (!arguments[0]) {
    throw new Error("one argument is needed");
  }
  _ref = arguments[0], ruleGenerator = _ref.ruleGenerator, contextGenerator = _ref.contextGenerator;
  if (!ruleGenerator) {
    throw new Error("ruleGenerator needs to be supplied");
  }
  contextGenerator || (contextGenerator = function(req, callback) {
    callback(null, req);
  });
  return function(req, res, next) {
    ruleGenerator(function(err, rules) {
      if (err) {
        rules = {};
      }
      contextGenerator(req, function(err, context) {
        if (err) {
          next(err);
          return;
        }
        req._featureFlags = FeatureFlagCollection.generate({
          rules: rules,
          context: context
        });
        return next();
      });
    });
  };
};
